### ISSUE TITLE
Checklist for SPAdes 4.0 release

### ISSUE THREAD

**Issue by asl** [ablab/spades#1296]
- [x] #1301
- [x] Update version
- [x] #1302
- [x] #1292 
- [x] #1293 
- [x] #1295 
- [x] #1294
- [x] Email notifications if possible
- [x] #1303
- [x] #1298 
- [x] Move Pathracer README to docs
- [x] Merge SPAligner README with docs

**Comment by asl** [comment]
Release was made: https://github.com/ablab/spades/releases/tag/v4.0.0
